// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1ozcM2GgMYBetAYP_7Zht2iNINF3YIAA',
    appId: '1:498719774580:web:995121b3a4266f4747be21',
    messagingSenderId: '498719774580',
    projectId: 'newsplus-8408b',
    authDomain: 'newsplus-8408b.firebaseapp.com',
    storageBucket: 'newsplus-8408b.appspot.com',
    measurementId: 'G-04GXPVDN5N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKZg-svVrSwoLvicdmWLS6gzyaknQ_RlM',
    appId: '1:498719774580:android:7cc0a21c7a828f9a47be21',
    messagingSenderId: '498719774580',
    projectId: 'newsplus-8408b',
    storageBucket: 'newsplus-8408b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnK7JfxGe-D323MpVkGk25ZSOjrviXgzc',
    appId: '1:498719774580:ios:f3af0539abcd06c647be21',
    messagingSenderId: '498719774580',
    projectId: 'newsplus-8408b',
    storageBucket: 'newsplus-8408b.appspot.com',
    iosClientId: '498719774580-64p2chcffae0bo61rcg1no57oq2gpgtd.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsplus',
  );
}
